spring:
  application:
    name: studai

  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    username: devuser
    password: devpassword

  flyway:
    sql-migration-prefix: 20
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    user:
      name: studai_user
      password: studai_password

server:
  port: 5000

assistant:
  base-uri: http://127.0.0.1:8000/api
  openai-api-key: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
