# .github/workflows/build.yml
name: Build and Test

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
      - name: Run tests with Maven
        run: mvn test --file pom.xml
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: studai-backend
          path: target/studai-1.0.0.jar
